"""empty message

Revision ID: ed08f1c4ee6c
Revises: 
Create Date: 2019-03-22 11:04:00.556006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed08f1c4ee6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('mail', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dream',
    sa.Column('idDream', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('adress', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('travel', sa.Boolean(), nullable=False),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('infoTransport', sa.Text(), nullable=True),
    sa.Column('costTransport', sa.Float(), nullable=True),
    sa.Column('accommodation', sa.Text(), nullable=True),
    sa.Column('costAccommodation', sa.Float(), nullable=True),
    sa.Column('whatTodo', sa.Text(), nullable=True),
    sa.Column('whereToEat', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('idDream')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dream')
    op.drop_table('user')
    # ### end Alembic commands ###
